### ISSUE TITLE
handle tokenization errors

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#101] opened 2020-12-24 15:58 UTC
with alpheios-project/tokenizer#26 and alpheios-project/alpheios-core#590

When the tokenizer returns a 400 error, we should display the corresponding message to the user in a notification.

When the tokenizer returns a 500 error, we should display an unexpected system error message to the user  in a notification

**Comment by irina060981** [comment] 2020-12-29 11:10
There is no need to make changes alignment-editor code for this issue.

**Comment by irina060981** [comment] 2020-12-30 01:22
I would like to be able to distinguish 400 errors from 500 errors here.

400 errors from the tokenization service are those that are invalid input, and most likely (assuming no bugs) to be problems with the user input.

500 errors are system errors and most likely to be either bugs or service failures.

I think they should be differentiated for the user somehow.

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/pull/106#discussion_r549690770_

**Comment by irina060981** [comment] 2020-12-30 07:59
@balmas, could you advice me how to emulate 500 Error for testing? May be we would create some specific test case, that will always return 500 Error for testing?

I think that it is worth to create the third notification variant.

For now I have 2 types of Notifications:
- `error` - orange notification,
- `info` - blue notification

May be it is worth to add `system error` ?
It would have red color, and may be we should add a text that we would like a user would send to alpheios email.

For example, 
```
Please, send this error description to our email - support@alpheios.net

Tokenization service 500 Error (datetime)
Text: ....
Fetch parameters: ....
```

what do you think ?

**Comment by balmas** [comment] 2020-12-31 15:02
that's an interesting idea re sending the email (although I think we probably should allow the user to click a button to send directly rather than asking them to send the email themselves -- but that requires alpheios-project/alpheios-core#116 ) let's make that a separate issue because I don't think we will do it in the first release of the alignment editor.

As for how to generate a 500 error, ideally we shouldn't get any since these are unexpected errors :-)  Need to think about the best way to generate one.

**Comment by irina060981** [comment] 2021-01-04 07:31
Created a separate issue for emailing errors
https://github.com/alpheios-project/alignment-editor-new/issues/111

**Comment by irina060981** [comment] 2021-01-04 07:31
>As for how to generate a 500 error, ideally we shouldn't get any since these are unexpected errors :-) Need to think about the best way to generate one.

Then I would emulate it for testing - and will update with real examples :)

**Comment by irina060981** [comment] 2021-01-06 04:54
Merged and closed

**Closed by irina060981** 2021-01-06 04:54 UTC
Labels: bug, waiting-merge

**Comment by irina060981** [comment] 2021-01-25 02:53
@monzug , I don't know how to reproduce errors from tokenizer now (from user's input), because for now it tokenizes without any complaints :)
May be you know situations with user inputs when it should return errors?

**Comment by monzug** [comment] 2021-01-27 14:39
a challenge for me. let me try!

**Comment by monzug** [comment] 2021-01-27 14:48
1) example of user error: "Request doesn't return data - 400: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1) (tokenizationGroup.alpheios.getTokens)"

**Comment by irina060981** [comment] 2021-01-28 08:59
oh great - then it works - a detailed message is printed

**Comment by irina060981** [comment] 2021-01-28 09:03
As for 500 Error - I could use an error with chinese - as it fails in tokenizer with 500 Error

**Comment by monzug** [comment] 2021-01-28 10:38
Super, I will do that then

**Comment by irina060981** [comment] 2021-01-28 11:24
ok, I have made some checks and fixes - it should look like this

500 Error example (chinese)
![image](https://user-images.githubusercontent.com/12377640/106131940-05d5c980-61af-11eb-86d9-075862f8f788.png)

400 Error example (tei)
![image](https://user-images.githubusercontent.com/12377640/106131995-18500300-61af-11eb-8fa6-eb3670c43440.png)

**Comment by monzug** [comment] 2021-01-28 13:16
Ok I got the 500 error in the console log
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
and Request doesn't return data - 500: (tokenizationGroup.alpheios.getTokens) 

however I am not getting the 500 message above if I have more than 1 line - the following one is generated "Unable to get data from url - https://tools.alpheios.net/tokenizer/tokenize/text?lang=zh&direction=ltr&segments=doubleline (tokenizationGroup.alpheios.getTokens)"

@irina060981 , any idea why such a difference just by adding a new line?

**Comment by irina060981** [comment] 2021-01-29 02:04
@monzug , I didn't quite understand what test case did you use?

There were some delays in updating the link with updated version of https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html
I think that there were some problems with github yesterday.

For now my test case works well

![image](https://user-images.githubusercontent.com/12377640/106221853-1d05cd00-622a-11eb-9e5d-0fbae7bf5d53.png)

**Comment by monzug** [comment] 2021-01-29 06:23
@irina060981 , you are right. I am only getting the 500 message now. it could have been github delays.  this one is verified.
