### ISSUE TITLE
Previous text is not refresh from Translation box

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#411] opened 2021-05-28 16:24 UTC
this is an awkward scenario, and I remembered we had this issue in the past:
1) upload a tsv file for original and translation but do not align the text 
2) then from slide menu, go to resume a previous alignment and choose an other .tsv file
3) you will see the Translation box has an extra entry from the previous Translation text.
I was only able to repro with .tsv files.
it should refresh the screen when I go to Resume previous alignment.

![Screen Shot 2021-05-28 at 6 34 21 PM](https://user-images.githubusercontent.com/41396793/120015191-5802ec00-bfe3-11eb-9cc4-ed765673d451.png)

**Comment by monzug** [comment] 2021-05-31 12:26
an other example. Go to resume previous alignment from the splash screen and select a json file with 3 languages. From file type is not possible to understand if it's a full alignment json file or not

1) Enter text - this is the case that it's not a full alignment
![Screen Shot 2021-05-31 at 2 16 21 PM](https://user-images.githubusercontent.com/41396793/120192370-663b4d00-c21b-11eb-9aaf-45df36bf999d.png)

2) Align text - align text is populated by a previous alignment
![Screen Shot 2021-05-31 at 2 16 32 PM](https://user-images.githubusercontent.com/41396793/120192563-9f73bd00-c21b-11eb-94f1-070cfaddaee9.png)

**Comment by irina060981** [comment] 2021-07-05 08:00
I tried to reproduce both:

1.
>this is an awkward scenario, and I remembered we had this issue in the past:
upload a tsv file for original and translation but do not align the text
then from slide menu, go to resume a previous alignment and choose an other .tsv file
you will see the Translation box has an extra entry from the previous Translation text.
I was only able to repro with .tsv files.
it should refresh the screen when I go to Resume previous alignment.

First of all I would like to point that there was decided not to support download to tsv and upload from tsv (we don't have ability to download to tsv). 
Anyway when I tried to reproduce this scenario - I didn't see described bug. There was another bug (with printing an error to console). I fixed it. 
I was not able to reproduce your case.

**Comment by irina060981** [comment] 2021-07-05 08:03
>an other example. Go to resume previous alignment from the splash screen and select a json file with 3 languages. From file type is not possible to understand if it's a full alignment json file or not

I have already fixed filename for tokenized and not tokenized aignment.

**Comment by irina060981** [comment] 2021-07-05 08:09
I was not able to understand the second scenario - could describe steps more clear.
As I could see from screenshots - Edit text screen shows already aligned origin and 1 tranlation text.
And a new added translation text - that is not aligned.
And it is not shown on the Aligned Text screen (as it is not tokenized).

In the attachment - I see a file with more then 3 languages.
So I don't understand what steps should I do to reproduce the problem - resume another alignment and previous text is still in the translation textarea.

I tried - to upload a json with 3 not tokenized texts.
Align it.
And then resume with another untokenized json with two texts.
Everything was cleared well.
May be it is already solved.
Waiting your verification.

**Comment by monzug** [comment] 2021-07-05 14:29
> I tried to reproduce both:
> 
> 
> > this is an awkward scenario, and I remembered we had this issue in the past:
> > upload a tsv file for original and translation but do not align the text
> > then from slide menu, go to resume a previous alignment and choose an other .tsv file
> > you will see the Translation box has an extra entry from the previous Translation text.
> > I was only able to repro with .tsv files.
> > it should refresh the screen when I go to Resume previous alignment.
> 
> First of all I would like to point that there was decided not to support download to tsv and upload from tsv (we don't have ability to download to tsv).
> Anyway when I tried to reproduce this scenario - I didn't see described bug. There was another bug (with printing an error to console). I fixed it.
> I was not able to reproduce your case.

Irina, I know it has been decided to not support download of tsv files but as far as I know we still do support the upload of tsv files as you can see from following message. If there was a decision to not support uploading tsv files, we should remove all references to tsv from user interface and pls, enter a github so we are all aware of it.

![Screen Shot 2021-07-05 at 4 23 15 PM](https://user-images.githubusercontent.com/41396793/124486292-bb83f480-ddad-11eb-90cc-05fa9d993f03.png)

Do I need to do any testing on the error on console that you have fixed?

**Comment by monzug** [comment] 2021-07-05 14:59
as per second scenario, it was not refreshing the text of the original (as you can see from screenshot the arabic was populated by previous text in the align text screen), you can easily see yourself by using the attached zip file above.

I do believe that this one has been fixed as per scenario 1 as the refreshing of previous text is now happening.

**Comment by irina060981** [comment] 2021-07-06 10:48
>Irina, I know it has been decided to not support download of tsv files but as far as I know we still do support the upload of tsv files as you can see from following message. If there was a decision to not support uploading tsv files, we should remove all references to tsv from user interface and pls, enter a github so we are all aware of it.

Download interface was limited to json/html in this issue - https://github.com/alpheios-project/alignment-editor-new/issues/376
I didn't erase specifically an ability to upload from previous tsv files for you, Monica.
As I know that you still use it.
But users won't be able to upload from tsv files because they won't be able to create it from interface.

That's why there was a bug, that I didn't update upload from tsv for IndexedDB support.
This bug is fixed - and if you could upload tsv without a failure - then this error is fixed.
So I don't think that you need to test it specifically. If you won't be able to resume an alignment - you would create  bug issue.

**Comment by monzug** [comment] 2021-07-07 16:05
Irina, let's wait Harry's feedback on tsv. he was supposed to discuss if  tsv files are popular with some professors. Based on the call we had, my understanding is that we will not be able to support tsv file created outside Alpheios environment. I agree with you that we should remove any reference to tsv from interface but can this task wait till next week?

**Comment by irina060981** [comment] 2021-07-08 00:23
I have no reasons to bein hurry :)

**Comment by monzug** [comment] 2021-07-08 15:15
Thanks!

**Comment by irina060981** [comment] 2021-09-30 02:16
@monzug , do you have some suggestions here?
or may be we could close this issue?

**Comment by irina060981** [comment] 2021-10-11 03:17
Removed 
![image](https://user-images.githubusercontent.com/12377640/136728465-5dadcfc5-887b-430e-9312-b2758bf62b13.png)

**Comment by irina060981** [comment] 2021-10-13 03:26
Fixed

**Closed by irina060981** 2021-10-13 03:26 UTC
Labels: bug
