### ISSUE TITLE
Question on TEI elements

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#114] opened 2021-01-05 15:13 UTC
@irina060981 Irina, if I change any of the TEI elements, is there a way to go back to the default elements such as body or p,div,seg,l,ab or label,ref,milestone,orig,abbr,head,title,teiHeader,del,g,bibl,front,back,speaker? if I reload the page, the most recent changes are still sticky. Is it by design, right?

**Comment by balmas** [comment] 2021-01-05 15:26
It is by design. I think the next build will have a reset options feature.

**Comment by monzug** [comment] 2021-01-05 15:27
thanks. I saved the default on a file for now, just in case...

**Comment by irina060981** [comment] 2021-01-06 05:10
There are two variants to clear saved options:

1. From the user perspective : I have added Reset all button to the options block:
![image](https://user-images.githubusercontent.com/12377640/103731219-5b93d780-5030-11eb-8bcc-287d59415c19.png)

It would reset global options and options for the each text instance

2. From the developer perspective:
You could do the same cleaning manually using browser

**Chrome**
1. Open Inspector - Right button mouse click -> Inspect (Ctrl+Shift+I)
2. Go to the Application tab and select Local Storage in the left list:

![image](https://user-images.githubusercontent.com/12377640/103731449-e96fc280-5030-11eb-8c4a-f95a036fd07e.png)

on the right you would see all saved options
Click right click mouse and select clear (in the left list -> Local Storage -> Site URL)

![image](https://user-images.githubusercontent.com/12377640/103731614-4bc8c300-5031-11eb-8d19-ab8fe1041048.png)

**Firefox**

**Comment by irina060981** [comment] 2021-01-06 08:19
> It is by design. I think the next build will have a reset options feature

It is done via https://github.com/alpheios-project/alignment-editor-new/pull/112

Will close this issue

**Closed by irina060981** 2021-01-06 08:19 UTC
Labels: question
