### ISSUE TITLE
cannot save locally a json file in safari

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#537] opened 2021-09-16 13:45 UTC
related to #521
tested in safari/Mac
after editing and inserting words in edit text, I tried to save locally a file, but it worked only with HTML output, not json. See screenshot for error in the log. I tried to reproduce it but could not. Irina, does this error give you any clue?

![Screen Shot 2021-09-16 at 3 04 30 PM](https://user-images.githubusercontent.com/41396793/133623331-f3f96461-9fc4-4d9d-bbbe-d4053df8f820.png)

this is the build #
![Screen Shot 2021-09-16 at 3 04 48 PM](https://user-images.githubusercontent.com/41396793/133623410-63f422fc-9959-471e-8c28-f2b7312b1a96.png)

**Comment by monzug** [comment] 2021-09-16 16:54
I got a similar error when I resume an indexedDB file in Chrome/safari. could they be related?

![Screen Shot 2021-09-16 at 6 53 26 PM](https://user-images.githubusercontent.com/41396793/133653615-ab405b30-628f-42ba-ba21-91af60550b77.png)

**Comment by irina060981** [comment] 2021-09-17 00:24
This error means that there is an annotation that is not connected to the token.
I could not reproduce suc an error.

Could you check annotations for the alignment where you see such an error?
I would add a check later - so such wrong annotations would be skupped for saving.
But it is useful to understand what exactly creates this error

**Comment by monzug** [comment] 2021-09-17 05:39
good to know that it had to do with annotations. will try to repro. thanks

**Comment by monzug** [comment] 2021-09-17 12:58
again I could not save locally. See below the screenshot - to narrow down the issue, I did only use annotations
![Screen Shot 2021-09-17 at 2 49 11 PM](https://user-images.githubusercontent.com/41396793/133786238-889b5d40-bd81-4b72-ba32-b68cb72bb58c.png)

**Comment by irina060981** [comment] 2021-09-19 03:03
If you click on the error in Chrome console - it will show the same details.
Could you give me more information about annotations that are defined here - may be screenshot them?

**Comment by monzug** [comment] 2021-09-19 07:51
in chrome/Mac. I just edited a token with annotation by adding a new word, so the original annotation is lost. then I add an annotation to the newly created token. see the error in the log and the new annotation
![Screen Shot 2021-09-19 at 9 48 28 AM](https://user-images.githubusercontent.com/41396793/133919734-d49899d1-7f5d-41ca-87fc-53dea7a65c32.png)
![Screen Shot 2021-09-19 at 9 48 09 AM](https://user-images.githubusercontent.com/41396793/133919735-1bf392f1-4dae-4788-ba98-f19efa37c498.png)

**Comment by monzug** [comment] 2021-09-19 07:55
as said the html output is saved correctly. see below
[19-09_09-53-alignment-html-output-grc-grc.html.zip](https://github.com/alpheios-project/alignment-editor-new/files/7191224/19-09_09-53-alignment-html-output-grc-grc.html.zip)

**Comment by irina060981** [comment] 2021-09-19 08:40
Oh, thank you, Monica, for explanation - I think, I know what is the problem here - will fix it after undo/redo

**Comment by monzug** [comment] 2021-09-19 10:01
Great! It is not probably what I did originally but this was the only way to replicate the issue of not been able to save locally. Hope you can find the solution.

**Comment by monzug** [comment] 2021-09-20 13:50
exact steps to repro the scenario in which I cannot save locally: add an annotation to a token, then go to edit a merge the token with a comma (e.g.), go back to annotation and add a new annotation to the 'new token' then click on save locally. file will not be saved with error: Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.token.convertToShortJSON')

**Comment by irina060981** [comment] 2021-09-24 02:43
This issue is connected with this - https://github.com/alpheios-project/alignment-editor-new/issues/538

**Comment by irina060981** [comment] 2021-09-24 02:49
I have realized the following rules for edititng tokens with annotations:

1. update token word, move to segment, change line break - annotations are still saved with the edited token
2. delete token - deletes connected annotations, undo - restores deleted annotations
3. merge tokens - saves all annotations to the result tokens - undo - divides annotations as it was before, annotations from merged token are saved to the base token
4. split token - saves all tokens to the first token

Undo/redo works

**Comment by monzug** [comment] 2021-09-24 15:45
I am able to save locally now. yeahhh.
just a question: the annotation for a token is kept also when the token is merge to an other word to create a different token and new annotations are added to the newly created token. I think this is ok. User can always delete the annotation related to the old token. do you agree, right?
![Screen Shot 2021-09-24 at 5 34 39 PM](https://user-images.githubusercontent.com/41396793/134702646-4e14b7dd-e57a-4a39-ac25-634108daee59.png)

**Comment by monzug** [comment] 2021-09-24 16:06
anyhow I can save locally now, so this issue is fixed. we might need a new issue for this specific scenario.

**Comment by irina060981** [comment] 2021-09-27 04:18
Yes, I think that your question is out of issue's scope.
And I need some exact scenario what to do.

Realized workflow is based on the concept - we don't erase any created annotations, if after editing tokens there would be outdated annotations - a user would delete them.
Each token edit is changing a token and it becomes a new token, but an application doesn't do any conclusions what annnotations should  be erased. Undo/Redo simply repeats the previous state whiout any analysis.

If you want to add some rules when an application should erase annotations - you should create a new issue with exact conditions. And I would do based on your rule.

But from my point of view it is not a correct behaviour from the application - to erase annotations that were created by the user who changed tokens.

Anyway I suggest to close this issue

**Closed by irina060981** 2021-09-27 04:18 UTC
Labels: bug

**Comment by monzug** [comment] 2021-09-27 05:33
oh no, I do not want to erase annotation but to preserve the same behavior as UNDO does. in the scenario described above, the base or original annotated word has still the annotation saved(which is correct) but link to an other word. see the screenshots above to understand the issue. this can be done after Pietro's release, of course.

**Comment by irina060981** [comment] 2021-09-27 08:14
>but link to an other word. see the screenshots above

What do you mean saying link to another word?
All properties are saved (number, text) but it is connected to a new token.
There is no link to any other token.

I don't see something that you see?
