### ISSUE TITLE
FF: text was rearranged in segmentation

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#55] opened 2020-10-29 15:33 UTC
interesting situation. see screenshot

![re-arrange-lines-FF](https://user-images.githubusercontent.com/41396793/97594765-5f283400-19d9-11eb-9f80-b466d85dbb2b.JPG)

I realized that the numbers of line in segmentations where different than the origin text, so I noticed that few lines were merged.  (e.g. soles occidere et redire possunt: merged with omnes unius aestimemus assis! and few others)
this is in FF/PC.  I thought it could be because of the extra space between lines but apparently it's not that.

**Comment by balmas** [comment] 2020-10-29 19:40
assigned to @irina060981

**Comment by irina060981** [comment] 2020-11-01 06:51
I was not able to reproduce both in Chrome and Firefox
![image](https://user-images.githubusercontent.com/12377640/97796784-12a35980-1c62-11eb-8a17-6fa864f4e9ef.png)

I used `Enter` for new line break.
I believe that in Monica's example was passed some other character that was not defined as line break inside remote tokenization service.

@balmas , we have some problems with line breaks in remote tokenizaion service (not only this case), what characters exactly is used as line break in remote service?

**Comment by balmas** [comment] 2020-11-02 15:41
@irina060981 as discussed today the tokenizer supports only the newline character (`\n`) for both single and double lines.  You can see this at:

https://github.com/alpheios-project/tokenizer/blob/master/tokenizer/lib/spacy/processor.py#L232
https://github.com/alpheios-project/tokenizer/blob/master/tokenizer/lib/spacy/processor.py#L246

As we discussed today, this needs to be made more robust.  However, I would prefer to keep the processor code as it is, and normalize other newline characters accordingly in a preprocessing step (e.g called from the service controller https://github.com/alpheios-project/tokenizer/blob/master/tokenizer/tokenizer.py)

**Comment by irina060981** [comment] 2020-11-04 11:41
Would be fixed with the PR

**Comment by irina060981** [comment] 2020-11-04 21:34
Merged and closed

**Closed by irina060981** 2020-11-04 21:34 UTC
Labels: question, waiting-merge
