### ISSUE TITLE
HTML output with singleline text in short, equivalence or sentence view

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#649] opened 2022-02-07 13:09 UTC
the html output of singleline text looks good in all views except in short, equivalence or sentence view - tested in Chrome and Safari
I was pretty sure that I have reported this issue in the past but I could not find any related github. if duplicated, feel free to close this one.
see below
![Screen Shot 2022-02-07 at 2 03 42 PM](https://user-images.githubusercontent.com/41396793/152794108-1ed9c542-13c9-47b0-8a84-c8eaf8b03e12.png)

**Comment by irina060981** [comment] 2022-02-21 08:28
@monzug , I was not able to reproduce - on the following

![image](https://user-images.githubusercontent.com/12377640/154916493-a1929c88-260a-4f8f-a967-cbb13fc73e82.png)

I need your html output with this problem and information about browser/OS, that you use

**Comment by monzug** [comment] 2022-02-21 12:45
reproducible in Chrome, FF and Safari/Mac. see attachment
![Screen Shot 2022-02-21 at 1 42 20 PM](https://user-images.githubusercontent.com/41396793/154957405-98e5dbe0-e948-41ae-97c2-fa50ab684431.png)

and the HTML output
[07-02_13-24-alignment-html-output-Monica's language-prima traduzione.html.zip](https://github.com/alpheios-project/alignment-editor-new/files/8109245/07-02_13-24-alignment-html-output-Monica.s.language-prima.traduzione.html.zip)

**Comment by monzug** [comment] 2022-02-21 13:06
an other view of a pretty large file
![Screen Shot 2022-02-21 at 2 06 31 PM](https://user-images.githubusercontent.com/41396793/154961121-3310c43b-f5fe-4732-9714-ad0e6c94c8d0.png)

**Comment by monzug** [comment] 2022-02-21 13:14
reproducible aslo in FF and Chrome/PC

![html-firefox](https://user-images.githubusercontent.com/41396793/154962380-6f8ce872-5de9-49bf-945c-f250237e5d35.JPG)

**Comment by irina060981** [comment] 2022-02-24 12:32
Thank you for the example - I was able to reproduce and fix

**Comment by monzug** [comment] 2022-02-24 13:54
short is fixed but equivalence and sentence look the same 
see below

![Screen Shot 2022-02-24 at 2 53 39 PM](https://user-images.githubusercontent.com/41396793/155537157-acae1594-9903-4ae0-91bd-16c303515891.png)

![Screen Shot 2022-02-24 at 2 53 23 PM](https://user-images.githubusercontent.com/41396793/155537167-c135522f-f915-41f2-8600-fba4c336e691.png)

**Comment by monzug** [comment] 2022-02-24 14:24
ah, note that this is also true for doubleline
see below

![Screen Shot 2022-02-24 at 3 23 51 PM](https://user-images.githubusercontent.com/41396793/155542326-d5aaa176-ade1-4306-a0f9-8d39b0eb34e9.png)

**Comment by irina060981** [comment] 2022-02-24 23:59
May be I missed something - will recheck - thank you for the catch

**Comment by irina060981** [comment] 2022-02-25 12:37
I checked - I didn't duplicate fix changes in all line views - it is fixed now in sentence and equivalence views

**Closed by irina060981** 2022-02-25 12:37 UTC
Labels: bug

**Comment by monzug** [comment] 2022-02-25 13:36
cannot test this at the moment because the html output with 2 translation is missing the side menu. Unfortunately I have saved long texts with only 2 translations. will wait for the fix.

**Comment by irina060981** [comment] 2022-02-28 04:35
it is fixed in #666
